# Generated by Django 5.2 on 2025-04-13 21:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarysubscription',
            name='activation_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
