# Generated by Django 5.1.6 on 2025-02-28 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ScheduleModel',
                'verbose_name_plural': 'ScheduleModels',
                'unique_together': {('date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicemodel')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.schedulemodel')),
            ],
            options={
                'verbose_name': 'BookingModel',
                'verbose_name_plural': 'BookingModels',
            },
        ),
    ]
