# Generated by Django 5.1.6 on 2025-03-08 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_web', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicemodel'),
        ),
        migrations.AddField(
            model_name='userform',
            name='Basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_web.basket'),
        ),
        migrations.AddField(
            model_name='userform',
            name='select_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.workschedule'),
        ),
    ]
