# Generated by Django 5.1.6 on 2025-03-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_web', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='basket',
        ),
    ]
