# Generated by Django 5.1.7 on 2025-03-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_web', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='successmodel',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='successmodel',
            name='scheduled_time_slot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
